language: php

sudo: false

branches:
  except:
    - release

branches:
  only:
    - master
    - develop

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: nightly

services:
  - mysql

before_install:
  - composer self-update
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - if [ -n "$GH_TOKEN" ]; then git config --global github.accesstoken ${GH_TOKEN}; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" && "$TRAVIS_PHP_VERSION" != "7.0" ]; then pecl channel-update pecl.php.net; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then printf "yes\n" | pecl install -f apcu-4.0.7; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "5.3" ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - echo 'apc.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS testrest_test;'
  - mysql -uroot -e 'GRANT ALL ON testrest_test.* TO '\''testrest'\''@'\''%'\'' IDENTIFIED BY '\''testrest'\'';'
  - mysql -uroot -e 'FLUSH PRIVILEGES;'
  - flags=""
  - if [ `phpenv version-name` == "5.3" ]; then flags="--ignore-platform-reqs"; fi
  - composer install --no-interaction $flags
  - composer require satooshi/php-coveralls:dev-master --no-interaction $flags

script:
  - make qa_all
  - make report

after_success:
  - cat ./target/report/phploc.txt
  - cat ./target/report/phpcompatinfo.txt

after_failure:
  - cat ./target/logs/junit.xml
  - cat ./target/report/phpcpd.txt

after_script:
 - "echo 'src_dir: src' > .coveralls.yml"
 - "echo 'coverage_clover: target/coverage/coverage.xml' >> .coveralls.yml"
 - "echo 'json_path: target/coverage/coveralls-upload.json' >> .coveralls.yml"
 - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then php vendor/bin/coveralls -v; fi;
